### PR TITLE
disable downloads where can_download = 0

### PR DESCRIPTION
**Pull request by hc5duke**
Hi, Hwan-Joon from Flickr here - I sent you an email regarding this. I took a look at the code and since you are calling getSizes, you don't even need to add extras. I've gone ahead with a simple change that disables downloads where prohibited. I didn't try to do too much on the UI end, but the logic should be simple and work the same for photos that can be downloaded. Please take a look at this as a starting point to make changes to your extension. Let me know if you have any questions.

### CODE REVIEW

**Comment by gil** [comment]
Hi Hwan-Joon, thank you for your help and quick Pull Request! I didn't realize there was a "candownload" parameter, I though the API would handle this kind of permission. Like when the user limits the original size and it's not available, do you know? Thank you for letting me know! I'll merge this PR and publish a updated version today!

**Comment by gil** [comment]
Hi Hwan-Joon, I've updated the code and the extension will be updated on the store in some hours. In my tests, I've found that many photos with candownload="0" are showing the download button when I open it on Flickr. Do you know why is that happening?

Like this photo:
https://www.flickr.com/photos/chung660326/14543711951/in/album-72157629541579930/

**Comment by gil** [comment]
The download button is shown right next to the favorite and share button. It will open all sizes for me, but the API says I can't download it. Is the "View all sizes" button only there to **view** the photo in all sizes, not **save** it?

**Comment by hc5duke** [comment]
Yeah - sorry that may be a bit confusing. The button is identical for "download" and "view all sizes for a photo that cannot be downloaded" currently.

**Pull request merged**
